runtime: nodejs8

instance_class: F2

env_variables:
        BUCKET_NAME: "devsite"

handlers:
        - url: /.*
          secure: always
          redirect_http_response_code: 301
          script: auto

